# Site settings
title: Alex Brown 
description: "A Mechanical Engineering post grad's thoughts on graduate school, working as a Computer Scientist, personal projects, and incorporating it into a busy life."
url: 'https://alexb7711.github.io'
# baseurl: '/blog'
google_analytics: 'UA-156354660-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alex Brown'
  email: alex.brown7711@gmail.com 
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  alexb7711
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
